"""Friend Bestie wordmark with the approved original ribbon symbol."""
from pathlib import Path
import json, shutil
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'output'/'identidad-v2'
PUBLIC=ROOT/'public'/'marca'
for directory in [OUT,OUT/'logos',OUT/'aplicaciones',OUT/'fuentes',PUBLIC]:directory.mkdir(parents=True,exist_ok=True)
SOURCE=ROOT/'output'/'identidad-exploracion-sans'/'fuentes'
fonts={w:TTFont(SOURCE/f'Poppins-{name}.ttf') for w,name in [(400,'Regular'),(600,'SemiBold'),(700,'Bold')]}
brand_font=TTFont(ROOT/'assets/fonts/friend-bestie/Friend Bestie.otf')
for f in SOURCE.glob('Poppins-*.ttf'):shutil.copy2(f,OUT/'fuentes'/f.name)
shutil.copy2(SOURCE/'poppins-OFL.txt',OUT/'fuentes'/'OFL.txt')
INK,PAPER,LIGHT,ACCENT,PINK='#171320','#F4F3F6','#F0EDF4','#9E1B3C','#E36285'

def outline(text,x,y,size=100,weight=700,spacing=0,font=None):
    font=font or fonts[weight];glyphs=font.getGlyphSet();cmap=font.getBestCmap();scale=size/font['head'].unitsPerEm
    pen=SVGPathPen(glyphs);cursor=x
    for i,char in enumerate(text):
        glyph=glyphs[cmap[ord(char)]];glyph.draw(TransformPen(pen,(scale,0,0,-scale,cursor,y)))
        cursor+=glyph.width*scale+(spacing if i<len(text)-1 else 0)
    return pen.getCommands(),cursor

def path(text,x,y,size=100,weight=700,color=INK):
    d,_=outline(text,x,y,size,weight);return f'<path fill="{color}" d="{d}"/>'
def rect(x,y,w,h,color):return f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" fill="{color}"/>'
def svg(body,w,h,label='Musicales.com.ar'):return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:g} {h:g}" role="img" aria-label="{label}">{body}</svg>'

# Original two-ribbon monogram, reconstructed as precise Bezier contours.
# No marquee frame, lamps or accent dots. Domain punctuation stays typographic.
markpath='M 0 81 V 48 C 0 17 28 8 47 27 C 59 39 63 53 63 81 C 45 78 42 60 39 52 C 33 33 23 39 23 49 V 81 Z M 51 24 C 71 12 100 22 100 53 V 81 H 76 V 57 C 76 42 61 30 51 24 Z'
main,cursor=outline('musicales',128,76,87,spacing=-.5,font=brand_font)
domain,cursor=outline('.com.ar',cursor+1,76,68,spacing=-.5,font=brand_font)
wordpath=main+' '+domain
dots=[]
W,H=cursor+4,100

def logo_body(dark=False,mono=False):
    ink=LIGHT if dark else INK;accent=ink if mono else PINK if dark else ACCENT
    return f'<path fill="{accent}" d="{markpath}"/><path fill="{ink}" d="{wordpath}"/>'
def mark_body(dark=False,mono=False):
    ink=LIGHT if dark else INK;accent=ink if mono else PINK if dark else ACCENT
    return f'<path fill="{accent}" d="{markpath}"/>'
def place_logo(x,y,width,dark=False):return f'<g transform="translate({x} {y}) scale({width/W})">{logo_body(dark)}</g>'
def place_mark(x,y,size,dark=False):return f'<g transform="translate({x} {y}) scale({size/100})">{mark_body(dark)}</g>'
def save(name,value): (OUT/name).write_text(value,encoding='utf-8')

for dark,label in [(False,'claro'),(True,'oscuro')]:
    for mono,suffix in [(False,''),(True,'-monocromatico')]:save(f'logos/logo-{label}{suffix}.svg',svg(logo_body(dark,mono),W,H))
    save(f'logos/isotipo-{label}.svg',svg(mark_body(dark),100,100))
save('aplicaciones/favicon.svg',svg(rect(0,0,100,100,INK)+place_mark(6,6,88,True),100,100))
save('aplicaciones/avatar.svg',svg(rect(0,0,320,320,INK)+place_mark(62,62,196,True),320,320))
og=rect(0,0,1200,630,INK)+place_logo(112,217,976,True)+path('Teatro musical argentino',112,440,34,400,LIGHT)
save('aplicaciones/open-graph.svg',svg(og,1200,630))
preview=rect(0,0,1600,950,PAPER)+path('Musicales.com.ar / Nueva identidad',70,70,23,600)
preview+=place_logo(85,183,1410)+path('Teatro musical argentino',87,459,31,400)
preview+=rect(0,550,1600,400,INK)+place_logo(85,683,1080,True)+place_mark(1330,660,180,True)
save('logo-nuevo.svg',svg(preview,1600,950,'Nueva identidad de Musicales.com.ar'))
for f in (OUT/'logos').glob('*.svg'):shutil.copy2(f,PUBLIC/f.name)
for name in ['favicon.svg','open-graph.svg']:shutil.copy2(OUT/'aplicaciones'/name,PUBLIC/name)
constants={'viewBox':f'0 0 {W:g} {H:g}','aspectRatio':W/H,'wordPath':wordpath,'dots':[],'markPath':markpath}
(ROOT/'src'/'lib'/'marca.ts').write_text('// Generated by scripts/identidad/build_brand_v2.py. Friend Bestie outlines; approved symbol unchanged.\nexport const MARCA = '+json.dumps(constants,ensure_ascii=False)+' as const;\n',encoding='utf-8')
print(f'Friend Bestie logo: {W:.1f} x {H}; current web SVGs and paths generated.')
